services:
  db:
    image: postgres:16-alpine
    container_name: pharmastock-db
    environment:
      POSTGRES_USER: pharmastock
      POSTGRES_PASSWORD: pharmastock
      POSTGRES_DB: pharmastock
    ports:
      - "5432:5432"
    volumes:
      - pharmastock_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmastock -d pharmastock"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pharmastock_pgdata:
